### ISSUE TITLE
Navigation Allows Navigation To Invalid Pages

### ISSUE THREAD

**Issue by NotNormal** [victor-valencia/bootstrap-iconpicker#10]
The class disabled only affects the styling of the buttons: the buttons continue to function. I added the following lines to the end of the updateButtonBar function to add the disabled attribute:
<code>
(page == 1) ? btn_prev.attr('disabled', 'disabled'): btn_prev.removeAttr('disabled');
(page == total_pages) ? btn_next.attr('disabled', 'disabled'): btn_next.removeAttr('disabled');
</code>

This makes sure I can't navigate off the end of the icon selection pages (pageNum <= 0 || pageNum > numPages)

**Comment by victor-valencia** [comment]
Hi @NotNormal.

This feature is available in:

[![v1.8.2](http://img.shields.io/badge/release-v1.8.2-blue.svg)](https://github.com/victor-valencia/bootstrap-iconpicker/releases/tag/v1.8.2).    
- Fix navigation to invalid pages.
- Filling search/hidden inputs.
- Search and filter case insensitive.
- Support for [Bootstrap 3.3.7](http://getbootstrap.com/).
- Update license to [MIT](https://github.com/victor-valencia/bootstrap-iconpicker/blob/master/LICENSE).

Regards.
