### ISSUE TITLE
Possible to load in custom icons?

### ISSUE THREAD

**Issue by emage** [victor-valencia/bootstrap-iconpicker#24]
Is it possible now or in the future to include custom icons created via iconmoon app or unicode?

**Comment by j4zz** [comment]
You can use any icon-set you have defined in your css. See the `iconset` options on the [documentation page](http://victor-valencia.github.io/bootstrap-iconpicker/).

For example if your icon css class is “emageicon” and your icons are defined as “emageicon-one”, “emageicon-two”,…

```js
$(".emage-iconpicker").iconpicker({
    iconset: {
      iconClass: 'emageicon',
      iconClassFix: 'emageicon-',
      icons: [ 'one', 'two']
    }
})
```

If you want to extend a given iconset by a few custom icons, I guess you would create a new font by loading the existing one and adding your custom icons, but there might be a more straight-forward/best practice way to do that.

**Comment by emage** [comment]
@j4zz  thanks!  What you suggested works like charm
