### ISSUE TITLE
Options to disabled Labels and pagination

### ISSUE THREAD

**Issue by emage** [victor-valencia/bootstrap-iconpicker#31]
Is there an option to disabled the  header and footer labels?  I simply want to show the icons.

If all the icons fit into a single page -- can the left and right arrow be hidden? 

All my icons fit on a single 10x10 row and col.

Thanks!

**Comment by emage** [comment]
I was able to disabled the header this way:

data-label-header=&quot;&quot; data-label-footer=&quot;&quot;

Prob wrong but works

**Comment by victor-valencia** [comment]
Try this: http://jsfiddle.net/victor_valencia/tqgem66f

Regards.
