### ISSUE TITLE
Supports Bootstrap 3.3?

### ISSUE THREAD

**Issue by onokazu** [victor-valencia/bootstrap-iconpicker#33]
This is a great plugin indeed. I just wanted to know that if this supports Bootstrap 3.3 as well? Also do you plan to update the fontawesome js file to version 4.3?

Thanks!

**Comment by victor-valencia** [comment]
Hi @onokazu.

This feature is available in:

[![v1.8.2](http://img.shields.io/badge/release-v1.8.2-blue.svg)](https://github.com/victor-valencia/bootstrap-iconpicker/releases/tag/v1.8.2).    
- Fix navigation to invalid pages.
- Filling search/hidden inputs.
- Search and filter case insensitive.
- Support for [Bootstrap 3.3.7](http://getbootstrap.com/).
- Update license to [MIT](https://github.com/victor-valencia/bootstrap-iconpicker/blob/master/LICENSE).

Regards.
