### ISSUE TITLE
Nav button not working properly

### ISSUE THREAD

**Issue by RushabhJoshi** [victor-valencia/bootstrap-iconpicker#35]
Hello,

iconpicker go beyond its icon limit

http://screencast.com/t/4uuvcciWu14p

when I click on this negative value appears. I think last previous icon should appear or don't go negative at all

thank you

**Comment by smartcorestudio** [comment]
It's here since Bootstrap 3.3.5 because of this: https://github.com/twbs/bootstrap/pull/16092
Since Bootstrap 3.3.5 you should add attribute "disabled" to disabled buttons.

**Comment by RushabhJoshi** [comment]
Thank you, and sorry for the late reply

**Comment by victor-valencia** [comment]
Hi @RushabhJoshi.

This feature is available in:

[![v1.8.2](http://img.shields.io/badge/release-v1.8.2-blue.svg)](https://github.com/victor-valencia/bootstrap-iconpicker/releases/tag/v1.8.2).    
- Fix navigation to invalid pages.
- Filling search/hidden inputs.
- Search and filter case insensitive.
- Support for [Bootstrap 3.3.7](http://getbootstrap.com/).
- Update license to [MIT](https://github.com/victor-valencia/bootstrap-iconpicker/blob/master/LICENSE).

Regards.
