### ISSUE TITLE
Paging 

### ISSUE THREAD

**Issue by theflashjordan** [victor-valencia/bootstrap-iconpicker#37]
I can page to pages that don't exist. Paging buttons show disabled color & cursor, but on click they page to empty grid..

**Comment by steveostudios** [comment]
I'm having this problem too...

**Comment by steveostudios** [comment]
Fixed this.
In bootstrap-iconpicker.js you need to fix the updateArrows function. You need to add the `disabled` property.

```
Iconpicker.prototype.updateArrows = function (page) {
        var op = this.options;
        var total_pages = this.totalPages();
        if (page === 1) {
            op.table.find('.btn-previous').addClass('disabled');
            op.table.find('.btn-previous').prop('disabled', true); // Add this
        }
        else {
            op.table.find('.btn-previous').removeClass('disabled');
            op.table.find('.btn-previous').prop('disabled', false); // And this
        }
        if (page === total_pages || total_pages === 0) {
            op.table.find('.btn-next').addClass('disabled');
            op.table.find('.btn-next').prop('disabled', true); // And this
        }
        else {
            op.table.find('.btn-next').removeClass('disabled');
            op.table.find('.btn-next').prop('disabled', false); // And this
        }
    };
```

Found it based on this issue: https://github.com/victor-valencia/bootstrap-iconpicker/issues/35

**Comment by rhyudek1** [comment]
merge and new release? :disappointed:

**Comment by plfort** [comment]
Any news about this bug ?

**Comment by cyberzilla** [comment]
i found this bug, this can fixed it

`Iconpicker.prototype.updateArrows = function (page) {
        var op = this.options;
        var total_pages = this.totalPages();
        if (page === 1) {
            op.table.find('.btn-previous').addClass('disabled').val('0');
        }
        else {
            op.table.find('.btn-previous').removeClass('disabled').val('-1');
        }
        if (page === total_pages || total_pages === 0) {
            op.table.find('.btn-next').addClass('disabled').val('0');
        }
        else {
            op.table.find('.btn-next').removeClass('disabled').val('1');
        }
    };`

**Comment by cyberzilla** [comment]
i found this bug, this can fixed it

> Iconpicker.prototype.updateArrows = function (page) {
        var op = this.options;
        var total_pages = this.totalPages();
        if (page === 1) {
            op.table.find('.btn-previous').addClass('disabled').val('0');
        }
        else {
            op.table.find('.btn-previous').removeClass('disabled').val('-1');
        }
        if (page === total_pages || total_pages === 0) {
            op.table.find('.btn-next').addClass('disabled').val('0');
        }
        else {
            op.table.find('.btn-next').removeClass('disabled').val('1');
        }
    };

**Comment by victor-valencia** [comment]
Hi @theflashjordan, @steveostudios, @rhyudek1, @plfort, and @cyberzilla.

This feature is available in:

[![v1.8.2](http://img.shields.io/badge/release-v1.8.2-blue.svg)](https://github.com/victor-valencia/bootstrap-iconpicker/releases/tag/v1.8.2).    
- Fix navigation to invalid pages.
- Filling search/hidden inputs.
- Search and filter case insensitive.
- Support for [Bootstrap 3.3.7](http://getbootstrap.com/).
- Update license to [MIT](https://github.com/victor-valencia/bootstrap-iconpicker/blob/master/LICENSE).

Regards.

**Comment by theflashjordan** [comment]
Thank you!
