### ISSUE TITLE
Need update to Font Awesome 4.4.0

### ISSUE THREAD

**Issue by princeofnaxos** [victor-valencia/bootstrap-iconpicker#39]
The iconset needs updating to FontAwesome 4.4.0.

**Comment by j0inty** [comment]
+1

**Comment by j05huamcclure** [comment]
Hello All,

I have added the 4.4.0 icon set.
https://gist.github.com/j05huamcclure/5ac1f779ec76c4e6fb86

**Comment by victor-valencia** [comment]
Hi @princeofnaxos, @j0inty and @jotty-mcclure.

This feature is available in:

[![v1.8.0](http://img.shields.io/badge/release-v1.8.0-blue.svg)](https://github.com/victor-valencia/bootstrap-iconpicker/releases/tag/v1.8.0).

- Fix for case, when there are no icons, and count is displayed, as '1 - 0 of 0 '. @[joews](https://github.com/joews).
- Support multiple versions (v4.3.0 @[michaelbilcot](https://github.com/michaelbilcot), v4.4.0, v4.5.0, v4.6.0 and v4.7.0) of [Font Awesome Icons](http://fontawesome.io/).

Regards.
