### ISSUE TITLE
Which files need to be hosted?

### ISSUE THREAD

**Issue by pvnr0082t** [victor-valencia/bootstrap-iconpicker#49]
Hi @victor-valencia ,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team, we want to host this project in cdnjs.
Could you please tell me if the files under [`bootstrap-iconpicker/js/iconset/`](https://github.com/victor-valencia/bootstrap-iconpicker/tree/master/bootstrap-iconpicker/js/iconset) need to be added in cdnjs? Thank you.

https://github.com/cdnjs/cdnjs/issues/8052

**Comment by victor-valencia** [comment]
Hi @pvnr0082t.

Thanks for upload this proyect in [cdnjs](https://github.com/cdnjs/cdnjs).

This files are required.

Please send me the links for includes this in documentation.

Regrads

**Comment by victor-valencia** [comment]
Hi @pvnr0082t .

I sent a request to the cdnjs repository.

[cdnjs/cdnjs#11594](https://github.com/cdnjs/cdnjs/pull/11594)

Regards.
