### ISSUE TITLE
Which license?

### ISSUE THREAD

**Issue by cocowalla** [victor-valencia/bootstrap-iconpicker#54]
The [license file](https://github.com/victor-valencia/bootstrap-iconpicker/blob/master/LICENSE) at the root of the repo is for the MIT license, as is the readme, and bower.json - but Javascript files contain a title block with the Apache 2.0 license.

I suggest one is chosen and applied across the repo.

**Comment by victor-valencia** [comment]
Hi.

Of course, i change the correct license to MIT.

Regards.

**Comment by victor-valencia** [comment]
Hi @cocowalla.

This feature is available in:

[![v1.8.2](http://img.shields.io/badge/release-v1.8.2-blue.svg)](https://github.com/victor-valencia/bootstrap-iconpicker/releases/tag/v1.8.2).    
- Fix navigation to invalid pages.
- Filling search/hidden inputs.
- Search and filter case insensitive.
- Support for [Bootstrap 3.3.7](http://getbootstrap.com/).
- Update license to [MIT](https://github.com/victor-valencia/bootstrap-iconpicker/blob/master/LICENSE).

Regards.
