### ISSUE TITLE
Problem Prev and Next button

### ISSUE THREAD

**Issue by iLenTheme** [victor-valencia/bootstrap-iconpicker#62]
Hello, I have a problem every time I press the "Prev" or "Next" button again, it will go away, which could be causing this error?
Take the example in a clean .html with just the necessary references.
Video: http://recordit.co/kYTM1dsIIv

**Comment by victor-valencia** [comment]
Hi @iLenTheme.

This feature is available in:

[![v1.8.2](http://img.shields.io/badge/release-v1.8.2-blue.svg)](https://github.com/victor-valencia/bootstrap-iconpicker/releases/tag/v1.8.2).    
- Fix navigation to invalid pages.
- Filling search/hidden inputs.
- Search and filter case insensitive.
- Support for [Bootstrap 3.3.7](http://getbootstrap.com/).
- Update license to [MIT](https://github.com/victor-valencia/bootstrap-iconpicker/blob/master/LICENSE).

Regards.
