### ISSUE TITLE
Font Awesome 5 Support?

### ISSUE THREAD

**Issue by 1e4** [victor-valencia/bootstrap-iconpicker#65]
Hi there,

Is there any intention that FA5 will supported? It's in Alpha 4 right now, so it shouldn't take any longer than August for them to release. Will it be officially supported?

**Comment by victor-valencia** [comment]
Hi @1e4 .

This feature is available in:

[![v1.10.0](http://img.shields.io/badge/release-v1.10.0-blue.svg)](https://github.com/victor-valencia/bootstrap-iconpicker/releases/tag/v1.10.0).    
- Support for [Bootstrap 4.x](http://getbootstrap.com/).
- Support for multiple versions of [Font Awesome Icons (Free and Pro)](http://fontawesome.io/). (v5.3.1, v5.3.1_pro)
- Support for [Weather Icons](http://erikflowers.github.io/weather-icons/). (v2.0.10)    
- Change default options:            
    - `arrowNextIconClass` = `fas fa-arrow-right` (Previous value: `glyphicon glyphicon-arrow-right`)
    - `arrowPrevIconClass` = `fas fa-arrow-left` (Previous value: `glyphicon glyphicon-arrow-left`)
    - `iconset` = `fontawesome5` (Previous value: `glyphicon`)
    - `unselectedClass` = `btn-secondary`. (Previous value: `btn-default`)
- Add file `bootstrap-iconpicker.bundle.min.js`, this file includes `bootstrap-iconpicker-iconset-all.min.js` and `bootstrap-iconpicker.min.js` files.

Regards.

**Comment by 1e4** [comment]
Oh man what a great notification to come back to. Glad you didn't forget. Thank you @victor-valencia
