### ISSUE TITLE
No icon?

### ISSUE THREAD

**Issue by USvER** [victor-valencia/bootstrap-iconpicker#7]
Configuration for no icon?

**Comment by erdemildiz** [comment]
You can add icons:[' ',"adjust",  iconset-fontawesome-4.2.0.js file

**Comment by ronenli** [comment]
In version 1.6.0:
- Add new empty string option to your iconset 'icons' array
- In 'bootstrap-iconpicker.js' switch line 147 with 148

**Comment by victor-valencia** [comment]
In the latest version, this feature is included.

- [![v1.7.0](http://img.shields.io/badge/zip-v1.7.0-blue.svg)](https://github.com/victor-valencia/bootstrap-iconpicker/archive/v1.7.0.zip).
    - Support for button and div tags.
    - All `iconset` includes the empty icon value.
    - Option `rows` accepts the value 0 to indicate all rows.
    - Add options: 
        - `align`
        - `header`
        - `footer`
    - Add methods: 
        - `setAlign`
        - `setHeader`
        - `setFooter`
    - Support for 1 more icon fonts:
        - [Material Design Icons v1.1.1](http://zavoloklom.github.io/material-design-iconic-font/)
