### ISSUE TITLE
FontAwesome 5

### ISSUE THREAD

**Issue by jrmessias** [victor-valencia/bootstrap-iconpicker#75]
Do you have a plan to add support for fontawesome 5?

**Comment by ngspinu** [comment]
Any updates on this one? Thanks!

**Comment by victor-valencia** [comment]
Hi @jrmessias and @ngspinu.

This feature is available in:

[![v1.10.0](http://img.shields.io/badge/release-v1.10.0-blue.svg)](https://github.com/victor-valencia/bootstrap-iconpicker/releases/tag/v1.10.0).    
- Support for [Bootstrap 4.x](http://getbootstrap.com/).
- Support for multiple versions of [Font Awesome Icons (Free and Pro)](http://fontawesome.io/). (v5.3.1, v5.3.1_pro)
- Support for [Weather Icons](http://erikflowers.github.io/weather-icons/). (v2.0.10)    
- Change default options:            
    - `arrowNextIconClass` = `fas fa-arrow-right` (Previous value: `glyphicon glyphicon-arrow-right`)
    - `arrowPrevIconClass` = `fas fa-arrow-left` (Previous value: `glyphicon glyphicon-arrow-left`)
    - `iconset` = `fontawesome5` (Previous value: `glyphicon`)
    - `unselectedClass` = `btn-secondary`. (Previous value: `btn-default`)
- Add file `bootstrap-iconpicker.bundle.min.js`, this file includes `bootstrap-iconpicker-iconset-all.min.js` and `bootstrap-iconpicker.min.js` files.

Regards.

**Comment by DirkOlten** [comment]
the setting "iconset = fontawesome5" only shows me the free iconset. How can I use the pro-set?

**Comment by migliori** [comment]
Hi & Many Thanks For Your Great & Useful Job!

Would it be possible that you upgrade to the latest Fontawesome (Version 5.11)?
